language: ruby
rvm:
  - "2.2.3"
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - rake db:create
  - rake db:migrate
  - rake db:test:prepare
script: bundle exec rspec spec
